// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: internal/planeroute/handlers/grpc/proto/planeroute.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescGZIP(), []int{0}
}

type ResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescGZIP(), []int{1}
}

func (x *ResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlaneRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaneId       int32                  `protobuf:"varint,1,opt,name=planeId,proto3" json:"planeId,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TicketsLeft   int32                  `protobuf:"varint,5,opt,name=ticketsLeft,proto3" json:"ticketsLeft,omitempty"`
	ArrivalTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=arrivalTime,proto3" json:"arrivalTime,omitempty"`
	DepartureTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=departureTime,proto3" json:"departureTime,omitempty"`
}

func (x *PlaneRouteRequest) Reset() {
	*x = PlaneRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaneRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaneRouteRequest) ProtoMessage() {}

func (x *PlaneRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaneRouteRequest.ProtoReflect.Descriptor instead.
func (*PlaneRouteRequest) Descriptor() ([]byte, []int) {
	return file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescGZIP(), []int{2}
}

func (x *PlaneRouteRequest) GetPlaneId() int32 {
	if x != nil {
		return x.PlaneId
	}
	return 0
}

func (x *PlaneRouteRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PlaneRouteRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PlaneRouteRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaneRouteRequest) GetTicketsLeft() int32 {
	if x != nil {
		return x.TicketsLeft
	}
	return 0
}

func (x *PlaneRouteRequest) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *PlaneRouteRequest) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

type PlaneRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlaneId       int32                  `protobuf:"varint,2,opt,name=planeId,proto3" json:"planeId,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TicketsLeft   int32                  `protobuf:"varint,6,opt,name=ticketsLeft,proto3" json:"ticketsLeft,omitempty"`
	ArrivalTime   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=arrivalTime,proto3" json:"arrivalTime,omitempty"`
	DepartureTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=departureTime,proto3" json:"departureTime,omitempty"`
}

func (x *PlaneRouteResponse) Reset() {
	*x = PlaneRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaneRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaneRouteResponse) ProtoMessage() {}

func (x *PlaneRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaneRouteResponse.ProtoReflect.Descriptor instead.
func (*PlaneRouteResponse) Descriptor() ([]byte, []int) {
	return file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescGZIP(), []int{3}
}

func (x *PlaneRouteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlaneRouteResponse) GetPlaneId() int32 {
	if x != nil {
		return x.PlaneId
	}
	return 0
}

func (x *PlaneRouteResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PlaneRouteResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PlaneRouteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaneRouteResponse) GetTicketsLeft() int32 {
	if x != nil {
		return x.TicketsLeft
	}
	return 0
}

func (x *PlaneRouteResponse) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *PlaneRouteResponse) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

var File_internal_planeroute_handlers_grpc_proto_planeroute_proto protoreflect.FileDescriptor

var file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDesc = []byte{
	0x0a, 0x38, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x8b, 0x02, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x4c, 0x65, 0x66,
	0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x40, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x9c, 0x02, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x4c, 0x65, 0x66, 0x74,
	0x12, 0x3c, 0x0a, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x40,
	0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x32, 0xaf, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x4c, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x12, 0x1d, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x50, 0x6c,
	0x61, 0x6e, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a,
	0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x6e,
	0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x55, 0x6e, 0x6c, 0x69, 0x74, 0x65, 0x73, 0x2f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescOnce sync.Once
	file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescData = file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDesc
)

func file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescGZIP() []byte {
	file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescOnce.Do(func() {
		file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescData)
	})
	return file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDescData
}

var file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_planeroute_handlers_grpc_proto_planeroute_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),          // 0: planeroute.EmptyRequest
	(*ResultResponse)(nil),        // 1: planeroute.ResultResponse
	(*PlaneRouteRequest)(nil),     // 2: planeroute.PlaneRouteRequest
	(*PlaneRouteResponse)(nil),    // 3: planeroute.PlaneRouteResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_internal_planeroute_handlers_grpc_proto_planeroute_proto_depIdxs = []int32{
	4, // 0: planeroute.PlaneRouteRequest.arrivalTime:type_name -> google.protobuf.Timestamp
	4, // 1: planeroute.PlaneRouteRequest.departureTime:type_name -> google.protobuf.Timestamp
	4, // 2: planeroute.PlaneRouteResponse.arrivalTime:type_name -> google.protobuf.Timestamp
	4, // 3: planeroute.PlaneRouteResponse.departureTime:type_name -> google.protobuf.Timestamp
	2, // 4: planeroute.PlaneRoute.AddPlaneRoute:input_type -> planeroute.PlaneRouteRequest
	0, // 5: planeroute.PlaneRoute.StreamCurrentRoutes:input_type -> planeroute.EmptyRequest
	1, // 6: planeroute.PlaneRoute.AddPlaneRoute:output_type -> planeroute.ResultResponse
	3, // 7: planeroute.PlaneRoute.StreamCurrentRoutes:output_type -> planeroute.PlaneRouteResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_planeroute_handlers_grpc_proto_planeroute_proto_init() }
func file_internal_planeroute_handlers_grpc_proto_planeroute_proto_init() {
	if File_internal_planeroute_handlers_grpc_proto_planeroute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaneRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaneRouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_planeroute_handlers_grpc_proto_planeroute_proto_goTypes,
		DependencyIndexes: file_internal_planeroute_handlers_grpc_proto_planeroute_proto_depIdxs,
		MessageInfos:      file_internal_planeroute_handlers_grpc_proto_planeroute_proto_msgTypes,
	}.Build()
	File_internal_planeroute_handlers_grpc_proto_planeroute_proto = out.File
	file_internal_planeroute_handlers_grpc_proto_planeroute_proto_rawDesc = nil
	file_internal_planeroute_handlers_grpc_proto_planeroute_proto_goTypes = nil
	file_internal_planeroute_handlers_grpc_proto_planeroute_proto_depIdxs = nil
}
